### ISSUE TITLE
java.io.IOException: Only uncompressed point format supported

### ISSUE THREAD

**Issue by donovanmuller** [fabric8io-images/java#8]
This issue is described at https://github.com/spring-cloud-incubator/spring-cloud-kubernetes/issues/60.

tl;dr Using tag 1.2.4+ you get weird SSL errors in certain cases.
For instance when using the [kubernetes-client](https://github.com/fabric8io/kubernetes-client)

```console
Caused by: java.security.ProviderException: java.io.IOException: Only uncompressed point format supported
	at sun.security.ec.ECKeyPairGenerator.generateKeyPair(ECKeyPairGenerator.java:147) ~[sunec.jar:1.8.0_121]
	at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:703) ~[na:1.8.0_121]
	at sun.security.ssl.ECDHCrypt.<init>(ECDHCrypt.java:78) ~[na:1.8.0_121]
	at sun.security.ssl.ClientHandshaker.serverKeyExchange(ClientHandshaker.java:724) ~[na:1.8.0_121]
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:281) ~[na:1.8.0_121]
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026) ~[na:1.8.0_121]
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:961) ~[na:1.8.0_121]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062) ~[na:1.8.0_121]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375) ~[na:1.8.0_121]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403) ~[na:1.8.0_121]
	... 105 common frames omitted
Caused by: java.io.IOException: Only uncompressed point format supported
...
```

Opening here to track it.

**Comment by rhuss** [comment]
Thanks, seems that the Alpine 8.121.13-r2 still has issues. Just downgraded to 8.121.13-r0 
and released 1.2.6 (should be available soon on Docker hub).

Could you please retry with this version if ? If this doesn't work I still have the option to downgrade to 8.111.14-r0 (which is Java 1.8.0_111 and which is known to have worked for quite some time). The reason why I still want to try 1.8.0_121 is that I wanted the latest security Java updates. 

However we might have to wait until the next 1.8 release bubblsd up to Alpine.

**Comment by donovanmuller** [comment]
Thanks, I'll have to test early next week as I can't interrupt for a redeploy right now.
I'll let you know how that goes...

**Comment by donovanmuller** [comment]
👍  I've just updated to 1.2.6 and all seems good to me

**Comment by rhuss** [comment]
Perfect, thanks for testing :)
